windowrule = match:class .*, suppress_event maximize
windowrule = match:class nm-connection-editor, float on

layerrule {
    name = waybar
    match:class = waybar
    blur = on
    blur_popups = on
}

layerrule {
    name = walker
    match:class = walker
    blur = on
    blur_popups = on
    dim_around = off # fix this
    ignore_alpha = 0.5
}

layerrule {
    name = swaync-control-center
    match:class = swaync-control-center
    blur = on
    blur_popups = on
    dim_around = off # fix this
    ignore_alpha = 0.5
}

layerrule {
    name = swaync-notification-window
    match:class = swaync-notification-window
    blur = on
    dim_around = off # fix this
    ignore_alpha = 0.5
}

layerrule {
    name = swayosd
    blur = on
    ignore_alpha = 0.5
}