exec-once = waybar
exec-once = hyprpaper
exec-once = systemctl --user start hyprpolkitagent
exec-once = foot --server
exec-once = walker --gapplication-service
exec-once = swayosd-server
exec-once = swaync
