exec-once = waybar
exec-once = dunst
exec-once = hyprpaper
exec-once = systemctl --user start hyprpolkitagent
exec-once = wl-paste --watch cliphist store
exec-once = foot --server
exec-once = walker --gapplication-service