# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

windowrule = float, class:nm-connection-editor

layerrule = blur, waybar
layerrule = blurpopups, waybar
layerrule = ignorezero, waybar

layerrule = blur, walker
layerrule = ignorezero, walker
layerrule = ignorealpha 0.5, walker

layerrule = blur, swaync-control-center
layerrule = blur, swaync-notification-window
layerrule = ignorezero, swaync-control-center
layerrule = ignorezero, swaync-notification-window
layerrule = ignorealpha 0.5, swaync-control-center
layerrule = ignorealpha 0.5, swaync-notification-window
